apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rahulbollu/flask-backend:v1    # replace with your image later
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
